// fe-clients/react-ts/src/App.tsx
//  code: add a enter key event that takes the 'prompt' and makes a http post request to localhost:3000/prompt using fetch. Take the json response and push it into the 'promptResults' list. Make sure to json.parse the response.results' it will be a json string.

import { useState } from 'react'
import reactLogo from './assets/react.svg'
import viteLogo from '/vite.svg'
import './App.css'

// Define the PromptResult type
type PromptResult = {
  prompt: string;
  results: Record<string, any>[];
  sql: string;
};

function App() {

  // State variables
    const [prompt, setPrompt] = useState<string>('');
  // Load promptResults from local storage or default to empty list
    const [promptResults, setPromptResults] = useState<PromptResult[]>(
      () => JSON.parse(localStorage.getItem('promptResults') || '[]')
    );

    // Function to handle the Enter key press
    function handleKeyPress(event: React.KeyboardEvent<HTMLInputElement>) {
      if (event.key === 'Enter') {
        handleSubmit();
      }
    }

    // Function to handle the submit action
    function handleSubmit() {
      fetch('http://localhost:3000/prompt', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ prompt }),
      })
      .then(response => response.json())
      .then(data => {
        const resultsParsed = {
          ...data,
          results: JSON.parse(data.results),
        };
        const newPromptResults = [...promptResults, resultsParsed];
        setPromptResults(newPromptResults);
        localStorage.setItem('promptResults', JSON.stringify(newPromptResults));
      })
      .catch(error => console.error('Error:', error));
    }
    
  return (
    <>
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Framework: React-TS</h1>
      <h2>TTYDB Prototype</h2>
      {/* Dark theme input and button */}
      <input
        type="text"
        value={prompt}
        onChange={(e) => setPrompt(e.target.value)}
        onKeyPress={handleKeyPress}
        className="dark-theme"
      />
      <button onClick={handleSubmit} className="dark-theme">Submit</button>

      
      {/* List of prompt results */}
      <div className="flex-col-gap">
        {promptResults.map((result, index) => {
          return (
            <section key={index} className="dark-theme">
              {/* Display the prompt used */}
              <p>Prompt: {result.prompt}</p>
              <pre>{JSON.stringify(result.results, null, 2)}</pre>
              <code>{result.sql}</code>
            </section>
          );
        })}
      </div>
    </>
  )
}

export default App

// fe-clients/svelte-ts/src/App.svelte
<!-- code: add a enter key event that takes the 'prompt' and makes a http post request to localhost:3000/prompt using fetch. Take the json response and push it into the 'promptResults' list. Make sure to json.parse the response.results' it will be a json string.  -->

<script lang="ts">
  import svelteLogo from "./assets/svelte.svg";
  import viteLogo from "/vite.svg";

  let prompt: string = "";
  type PromptResult = {
    prompt: string;
    results: Record<string, any>[];
    sql: string;
  };

  // code: load this from local storage or default to empty list
  let promptResults: PromptResult[] = JSON.parse(localStorage.getItem('promptResults') || '[]');

  async function handleKeyDown(event: KeyboardEvent) {
    if (event.key === "Enter") {
      try {
        const response = await fetch("http://localhost:3000/prompt", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({ prompt }),
        });
        if (!response.ok) {
          throw new Error(`HTTP error! status: ${response.status}`);
        }
        const data = await response.json();
        promptResults = [...promptResults, {
          prompt,
          results: JSON.parse(data.results),
          sql: data.sql,
        }];
        localStorage.setItem('promptResults', JSON.stringify(promptResults));
        // code: save promptResults to local storage
        prompt = ""; // Clear the prompt input after submission
      } catch (error) {
        console.error("Error fetching prompt results:", error);
      }
    }
  }
</script>

<main>
  <div>
    <a href="https://vitejs.dev" target="_blank" rel="noreferrer">
      <img src={viteLogo} class="logo" alt="Vite Logo" />
    </a>
    <a href="https://svelte.dev" target="_blank" rel="noreferrer">
      <img src={svelteLogo} class="logo svelte" alt="Svelte Logo" />
    </a>
  </div>
  <h1>Framework: Svelete-TS</h1>
  <h2>TTYDB Prototype</h2>
  <input
    type="text"
    bind:value={prompt}
    placeholder="Enter your prompt"
    on:keydown={handleKeyDown}
  />

  {#each promptResults as result (result.prompt)}
    <section>
      <h3>{result.prompt}</h3>
      <pre>{JSON.stringify(result.results, null, 2)}</pre>
      <code>{result.sql}</code>
    </section>
  {/each}
</main>

<style>
  .logo {
    height: 6em;
    padding: 1.5em;
    will-change: filter;
    transition: filter 300ms;
  }

  input,
  button,
  pre,
  section,
  code {
    background-color: #333;
    color: white;
    border: none;
    padding: 0.5em;
    margin: 0.5em 0;
  }

  input,
  button {
    font-size: 1rem;
  }

  pre,
  code {
    font-family: monospace;
  }
</style>
